#version: "3.9"
services:
  rasa:
    build: 
      context: ./rasa-server
      dockerfile: Dockerfile
    image: rasa-server
    container_name: chatbot-server
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./logs:/rasa-server/rasa/logs
    networks:
      - rasa-netowrk
    env_file:
      - .env
    command: [$TOKEN]
  app:
    build: 
      context: ./action-server
      dockerfile: Dockerfile
    image: action-server
    container_name: action-server
    restart: always
    volumes:
      - ./logs:/action-server/logs
    networks:
      - rasa-netowrk
    expose: 
      - 5055 

networks:
  rasa-netowrk:
    driver: bridge
