#version: "3.9"
services:
  rasa:
    build: rasa-server
    image: rasa-server
    container_name: chatbot-server
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    networks:
      - rasa-netowrk
  app:
    build: action-server
    image: action-server
    container_name: action-server
    restart: always
    networks:
      - rasa-netowrk
    expose: 
      - 5055 

networks:
  rasa-netowrk:
    driver: bridge
